# Verwende das offizielle MySQL-Basisimage aus dem Docker Hub
FROM mysql:latest

# Optional: Setze Umgebungsvariablen für den MySQL-Server
ENV MYSQL_ROOT_PASSWORD=admin1234
ENV MYSQL_DATABASE=defaultdb
ENV MYSQL_USER=localadmin
ENV MYSQL_PASSWORD=admin1234

# Optional: Kopiere eine SQL-Datei in den Container, die beim Start ausgeführt wird
# Beispiel: Wenn du eine "init.sql"-Datei im gleichen Verzeichnis wie dieses Dockerfile hast
COPY init-dev.sql /docker-entrypoint-initdb.d/

# Optional: Ändere die Standard-Portnummer des MySQL-Servers (standardmäßig 3306)
EXPOSE 3307:3306

# Optional: Führe zusätzliche Befehle während der Containererstellung aus
# Beispiel: Ändere den Zeichensatz und die Kollation für die Datenbank
RUN echo "character-set-server=utf8mb4" >> /etc/mysql/conf.d/docker.cnf
RUN echo "collation-server=utf8mb4_unicode_ci" >> /etc/mysql/conf.d/docker.cnf

# Optional: Führe zusätzliche Konfigurationsschritte aus, wenn nötig

# CMD ist in der offiziellen MySQL-Basisimage definiert und startet den MySQL-Server